title: hxloop
description: "A set of articles from my day to day findings."
meta_description: "ios, xcode, swift, articles. tips and tricks."

baseurl: ""
url: www.hxloop.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown

highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: "https://www.twitter.com/gauravkeshre"

social:
   github: hxloop
   twitter: hxl00p
   email: gyard01@gmail.com

google_analytics: 'UA-102071010-4'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
